leds: qpnp-haptics: Fix qpnp-misc header include path
The qpnp-misc header was moved under include/linux/qpnp/.

Update the include path to fix the build error:
    fatal error: linux/qpnp-misc.h: No such file or directory

This aligns the driver with the current header file organization.

Change-Id: I84e8cafbd865d5742ac74bd82c9ce7c32504b8ad
Signed-off-by: jmpfbmx <jmpf.bmx@gmail.com>