input: et510: Switch to timer_setup and add timer include
/home/jmpfbmx/android/lineage/22.2/kernel/sony/sdm660/drivers/input/misc/egistec/et510-spi.c:996:2: error: implicit declaration of function 'setup_timer' [-Werror,-Wimplicit-function-declaration]

Change-Id: I9ba870c3efec8d940f2bf3cfeefbef086b29c954
Signed-off-by: jmpfbmx <jmpf.bmx@gmail.com>